In [ ]:
from google.colab import drive
import os
DRIVE = '/gdrive'
WRK_DIR = DRIVE + '/MyDrive/Colab Notebooks/(Step 2) Normalized Images -> Unsupervised Features -> Conventional Classification'

drive.mount('/gdrive', force_remount=True)
os.chdir(WRK_DIR)

Mounted at /gdrive


In [ ]:
from keras.applications.vgg16 import VGG16, preprocess_input
from keras.preprocessing import image
import numpy as np
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from keras.layers import Dense, Flatten
from keras.models import Model
# Load VGG16 model
vgg_model = VGG16(weights='imagenet', include_top=False, input_shape=(1536, 2048, 3))
# x = Flatten()(vgg_model.output)

x = Flatten()(vgg_model.output)
features = Dense(1000, activation='softmax')(x)
model = Model(inputs=vgg_model.input, outputs=x)

# Define a function to extract features from an image
def extract_features(img_path):
    # Load the image
    img = load_img(img_path, target_size=(1536, 2048))
    # Convert the image to an array
    x = img_to_array(img)
    # Expand the dimensions of the array to match the input shape of the model
    x = np.expand_dims(x, axis=0)
    # Preprocess the input
    x = preprocess_input(x)
    # Extract features using the VGG16 model
    # features = vgg_model.predict(x)
    features = model.predict(x)
    # Flatten the features into a 1D array
    features = features.flatten()
    return features

58889256/58889256 [==============================] - 4s 0us/step


ResourceExhaustedError: ignored

In [ ]:
import tensorflow as tf
tf.keras.backend.clear_session() 

In [ ]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 1536, 2048, 3)]   0         
                                                                 
 block1_conv1 (Conv2D)       (None, 1536, 2048, 64)    1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 1536, 2048, 64)    36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 768, 1024, 64)     0         
                                                                 
 block2_conv1 (Conv2D)       (None, 768, 1024, 128)    73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 768, 1024, 128)    147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 384, 512, 128)     0   

In [ ]:
import os
import csv
import numpy as np
from keras.applications.vgg16 import VGG16, preprocess_input
from keras.preprocessing import image

# Define the paths to the image files
dest_path = '/gdrive/My Drive/Normalized_Images/'
categories = ['Benign', 'Normal', 'Invasive', 'InSitu']

# Create an empty dictionary to store the extracted features
features_dict = {}

# Loop through each category and extract the features for each image
for category in categories:
    src_path = dest_path + category + '/'
    files = os.listdir(src_path)
    i = 0
    for file in files:
        if file.endswith('.tif'):
            img_path = src_path + file
            features = extract_features(img_path)
            features_dict[file] = features
            print(i)
            i+=1

# Write the features to a CSV file
# with open('/gdrive/My Drive/image_features.csv', 'w', newline='') as csvfile:
#     writer = csv.writer(csvfile)
#     writer.writerow(['filename'] + ['feature{}'.format(i) for i in range(7*7*512)])
#     for file, features in features_dict.items():
#         writer.writerow([file] + list(features))

1/1 [==============================] - 15s 15s/step
0
1/1 [==============================] - 0s 486ms/step
1
1/1 [==============================] - 0s 327ms/step
2
1/1 [==============================] - 0s 334ms/step
3
1/1 [==============================] - 0s 335ms/step
4
1/1 [==============================] - 0s 333ms/step
5
1/1 [==============================] - 0s 333ms/step
6
1/1 [==============================] - 0s 332ms/step
7
1/1 [==============================] - 0s 335ms/step
8
1/1 [==============================] - 0s 335ms/step
9
1/1 [==============================] - 0s 334ms/step
10
1/1 [==============================] - 0s 332ms/step
11
1/1 [==============================] - 0s 330ms/step
12
1/1 [==============================] - 0s 329ms/step
13
1/1 [==============================] - 0s 333ms/step
14
1/1 [==============================] - 0s 331ms/step
15
1/1 [==============================] - 0s 333ms/step
16
1/1 [==============================] - 0s 334ms/step
17
1/1

In [ ]:
features.shape

(3072000,)

In [ ]:
# # Write the features to a CSV file
# with open('/gdrive/My Drive/image_features.csv', 'w', newline='') as csvfile:
#     writer = csv.writer(csvfile)
#     writer.writerow(['filename'] + ['feature{}'.format(i) for i in range(1572864)])
#     for file, features in features_dict.items():
#         writer.writerow([file] + list(features))

In [ ]:
# import csv

# with open('/gdrive/My Drive/image_features.csv', newline='') as csvfile:
#     reader = csv.DictReader(csvfile)
#     features_dict_new = {}
#     for row in reader:
#         filename = row['filename']
#         features = [float(row['feature{}'.format(i)]) for i in range(1572864)]
#         features_dict_new[filename] = features

In [ ]:
# # Create a sample dictionary
# my_dict = {'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]}

# # Convert the dictionary values to a numpy array
# my_array = np.array(list(my_dict.values()))

# print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
VGG_features = np.array(list(features_dict.values()))

In [ ]:
print(VGG_features.shape)

(400, 1572864)


In [ ]:
np.save('VGG_Extracted_Features.npy', VGG_features)